### ISSUE TITLE
Unnamed terms.

### ISSUE THREAD

**Issue by gjgoerke** [normativeai/frontend#61]
<img width="432" alt="Screen Shot 2019-07-05 at 11 09 59 AM" src="https://user-images.githubusercontent.com/40189873/60711687-b4ebe980-9f15-11e9-86fd-24122ae1ceda.png">
When terms are saved without explicit naming they are highlighted in white and this error shows, perhaps defaulting to the first word or _x_ words of the description could speed up document annotation? @shaolintl @lex-lex

**Comment by shaolintl** [comment]
This is actually a very interesting issue. Using the system, it occurred to me many times that the propositions are many times very similar to the text written. Therefore, it makes a lot of sense to guess the right proposition variables for the user.

One way of doing that is to order the words in the sentence according to frequency in the target language and then select the first 3-5 of lowest frequency (and below some threshold) and connect them in snake_case.

It seems to me that this should be done on the frontend side in order to allow the user to easily change that.

**Comment by gjgoerke** [comment]
That sounds like a great idea.

**Comment by gjgoerke** [comment]
I added a a checkbox for automatically making a term name, right now it just takes the first three words and connects them with snake case, you can see the changes in [this](https://github.com/gjgoerke/frontend/tree/default_term_name/src) branch. If we choose words based on a frequency list i'm guessing we don't want that file loaded client side?
